[package]
name = "testable"
version = "0.1.0"
edition = "2021"

[lib]
name = "testable"
path = "src/lib.rs"

[[bin]]
name = "my_testable_program"
path = "src/bin.rs"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde_json = "1.0.89"
once_cell = "1.16.0"
